### ISSUE TITLE
Can somebody explain restart-ability of the app after crash when using the binary build pack? 

### ISSUE THREAD

**Issue by palokam** [cloudfoundry/binary-buildpack#11]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

What version of the buildpack you are using?

If you were attempting to accomplish a task, what was it you were attempting to do?

What did you expect to happen?

What was the actual behavior?

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
Not buildpack-related. Addressed in Slack here: https://cloudfoundry.slack.com/archives/C02HWMDUQ/p1491438058841066
