### ISSUE TITLE
Release: binary-buildpack (Feb)

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/binary-buildpack#114]
Release reminder for binary-buildpack

* See [diff from latest version](https://github.com/cloudfoundry/binary-buildpack/compare/v1.1.1..develop) and validate if a release is required.
* Make sure the latest commit on  has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/binary-buildpack)
* Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

**Comment by arjun024** [comment]
https://github.com/cloudfoundry/binary-buildpack/releases/tag/v1.1.2
