### ISSUE TITLE
Where did dotnet go?

### ISSUE THREAD

**Issue by awdorrin** [cloudfoundry/binary-buildpack#118]
the V1.1.2 binary_buildpack for windows stack no longer has .net installed.
I don't see anything saying it was being removed?

**Comment by arjun024** [comment]
What do you mean? Can you be more specific with an example?
This buildpack simply runs binary programs. If you mean the .NET Framework, it's provided by the stack

**Comment by awdorrin** [comment]
Please disregard - I forgot that dotnet applications have to be bundled as 'self-contained' in order to run on the binary_buildpack. 
Jumping between too many different programs and wasn't keeping things straight.
