### ISSUE TITLE
Errors while running the binary-buildpack test suit

### ISSUE THREAD

**Issue by rakrup** [cloudfoundry/binary-buildpack#13]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
Running on local laptop - vagrant based pcf dev instance.
`
api endpoint:   https://api.local.pcfdev.io
api version:    2.82.0
`
What version of the buildpack you are using?
master branch

If you were attempting to accomplish a task, what was it you were attempting to do?
trying to run all the integration tests using machete

What did you expect to happen?
all tests to succeed.

What was the actual behavior?
there are test failures.

Please confirm where necessary:
* [x] I have included a log output
[Error Log](https://gist.github.com/rakrup/179f3a285025eb0510a7ab24abee0fd3)
* [x] My log includes an error message
Yes
* [x] I have included steps for reproduction
Yes

**Comment by sclevine** [comment]
Thanks @rakrup, we'll investigate.

**Comment by dgodd** [comment]
@rakrup I believe that the problem appeared due to the cf cli removing support for `has-diego-enabled`, which is a reasonable plan since we no longer support DEA. I have removed the case switch and now the `develop` branch only supports diego from the integration tests.

**Comment by sclevine** [comment]
Fixed on `develop`. Closing. Thanks @rakrup!
