### ISSUE TITLE
Buildpack fails when packaged with go 1.20

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/binary-buildpack#133]
**What version of the buildpack you are using?**
v1.1.3

**If you were attempting to accomplish a task, what was it you were attempting to do?**
1. Package the offline buildpack on a system using go 1.20.3
2. Upload the new buildpack to CF
3. Push the binary test app from cf-acceptance-tests

**What did you expect to happen?**
Staging should succeed

**What was the actual behavior?**
The buildpack threw the following errors:

    [STG/0] ERR /tmp/buildpacks/7d3e828e705dfe804f399b84000a6813/bin/supply: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/buildpacks/7d3e828e705dfe804f399b84000a6813/bin/supply)
    [STG/0] ERR /tmp/buildpacks/7d3e828e705dfe804f399b84000a6813/bin/supply: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/buildpacks/7d3e828e705dfe804f399b84000a6813/bin/supply)

This appears to be related to a change in go 1.20 with linking to system libraries, see https://github.com/cloudfoundry/smb-volume-release/commit/bf037f3d854eb430dced6bff13791ec02131f813.

**Please confirm where necessary:**
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction

**Comment by elovin** [comment]
I suppose you used the old cflinuxfs3 stack, cflinuxfs4 has a newer glibc version since it is based on ubuntu 22.04
