### ISSUE TITLE
source of binaries listed in manifest 

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/binary-buildpack#17]
Hi, my team would like to use binary-buildpack 1.0.17 and to approve that I've to analyze it's source code and the code of its dependencies chain, so be sure that they don't have problematic licenses.

But we were not able to discover the download location of some packages.

They are those listed at https://github.com/cloudfoundry/binary-buildpack/blob/v1.0.17/src/binary/vendor/github.com/cloudfoundry/libbuildpack/fixtures/manifest/fetch/manifest.yml:

thing, other thing, nonsemver, etc.

(except "godep v79" that we already know).

Could you please indicate me what they are and at which URL I can download their source code from?

Thanks a lot.

**Comment by luisapace** [comment]
I'm sorry, I've closed for mistake

**Comment by sclevine** [comment]
That is an example manifest for testing purposes. Note that the domain is "example.com".

**Comment by luisapace** [comment]
Ok, I see; so, is there a license for them? what is their license? the same of the manifest? thanks.

**Comment by sclevine** [comment]
They don't exist. The URLs themselves are test data and don't link anywhere. The "example.com" website is used for examples.

**Comment by luisapace** [comment]
thanks a lot!

**Comment by luisapace** [comment]
Hi, me again, I've two questions:

1) in the https://github.com/cloudfoundry/binary-buildpack/blob/v1.0.17/src/binary/vendor/github.com/cloudfoundry/libbuildpack/fixtures/manifest/standard/manifest.yml

I see reference to:
jruby  9.3.4
jruby  9.3.5
jruby  9.4.4

but I cannot found their source on the net, those versions seem to not exist, could you help me please? 

2) in the

https://github.com/cloudfoundry/binary-buildpack/blob/v1.0.17/src/binary/vendor/github.com/cloudfoundry/libbuildpack/packager/fixtures/bad/manifest.yml

AND 

https://github.com/cloudfoundry/binary-buildpack/blob/v1.0.17/src/binary/vendor/github.com/cloudfoundry/libbuildpack/packager/fixtures/good/manifest.yml

I see reference to:

ruby  1.2.3

but I cannot found its source on the net, this versions seems to not exist, could you help me please? 

Thanks again
