### ISSUE TITLE
source of binaries dotnet and dotnet-framework

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/binary-buildpack#19]
Hi, my team would like to use binary-buildpack 1.0.17 and to approve that I've to analyze it's source code and the code of its dependencies chain, so be sure that they don't have problematic licenses.

But we were not able to discover the download location of the source of some packages.

They are those listed at:

https://github.com/cloudfoundry/binary-buildpack/blob/v1.0.17/src/binary/vendor/github.com/cloudfoundry/libbuildpack/fixtures/manifest/standard/manifest.yml:

dotnet 1.0.0-preview2-003131
dotnet 1.0.0-preview2-003156
dotnet 1.0.0-preview2-1-003177
dotnet 1.0.0-preview3-004056
dotnet 1.0.0-preview4-004233
dotnet-framework 1.0.0
dotnet-framework 1.0.1
dotnet-framework 1.0.3
dotnet-framework 1.1.0

Could you please indicate me what they are and at which URL I can download their source code from?

Many thanks.

**Comment by sclevine** [comment]
Same as #18.

**Comment by luisapace** [comment]
thanks!
