### ISSUE TITLE
Question on https://github.com/cloudfoundry/binary-buildpack/issues/18 

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/binary-buildpack#21]
Hi, I'm opening a new issue because I don't know how to reopen any closed issue (sorry for that).

In the: 
https://github.com/cloudfoundry/binary-buildpack/issues/18 

I read (as said by Stephen Levine):

"Everything in fixtures is test data that isn't included in the buildpack. Those versions don't exist, as you've noticed".

May I kindly ask you to please clarify that? what do you mean with "everything"?  and what do you mean that isn't included in the buildpack? for example there is another "fixture" directory in the binary buildpack at https://github.com/cloudfoundry/binary-buildpack/tree/v1.0.17/fixtures. 

Finally, that is valid for all the other buildpacks? I mean: is it a standard rule that what is in fixtures is test data that isn't included in the buildpack? 

Thanks again.

**Comment by sclevine** [comment]
All of the contents in the `fixtures` directory in every Cloud Foundry buildpack is not included in the final buildpack artifact. It is made up test data that is only used to develop the buildpack. The references to dependencies in the `fixtures` directories are not references to real dependencies.

**Comment by luisapace** [comment]
So, if I've understood well - for example - none of the all the gems included in the source code at https://github.com/cloudfoundry/ruby-buildpack/tree/v1.7.15/fixtures/rails3_mri_200/vendor/cache
will be present in the final buildpack so that nobody will be able to access/download their code at runtime when it will use the buildpack?  

Thanks again.

**Comment by astrieanna** [comment]
@luisapace That is correct. When we package buildpacks, the fixtures directory is not included.
