### ISSUE TITLE
follow on of https://github.com/cloudfoundry/binary-buildpack/issues/21

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/binary-buildpack#22]
Hi, this is a comment for https://github.com/cloudfoundry/binary-buildpack/issues/21

that has been closed before I could add this comment and that I've added, but the issue has remained closed.

**This is for ALL directories with this name in ALL the buildpacks? because I see the name "fixtures" in a lot of positions, for example https://github.com/cloudfoundry/binary-buildpack/tree/master/src/binary/vendor/github.com/cloudfoundry/libbuildpack/fixtures

Thanks for your patience!**

**Comment by astrieanna** [comment]
@luisapace Yes, this is true for all the fixtures directories in all the buildpacks.

**Comment by luisapace** [comment]
Perfect, thanks a lot.
