### ISSUE TITLE
buildpack-packager binary distribution

### ISSUE THREAD

**Issue by drahnr** [cloudfoundry/binary-buildpack#23]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`)?
```
{
   "name": "",
   "build": "",
   "support": "https://support.run.pivotal.io",
   "version": 0,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "min_cli_version": "6.22.0",
   "min_recommended_cli_version": "latest",
   "api_version": "2.116.0",
   "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
   "app_ssh_host_key_fingerprint": "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443",
   "routing_endpoint": "https://api.run.pivotal.io/routing",
   "user": "989efafd-7b12-4108-8400-8ddb1800bd72"
}
cf version 6.37.0+a40009753.2018-05-25
```

What version of the buildpack you are using?
None, I can't make it compile.

If you were attempting to accomplish a task, what was it you were attempting to do?
Run a rust statically compiled binary as a service with cf generating a binary buildpack.

What did you expect to happen?
I wished for a binary distribution of buildpack-packager - I am not exactly a go-lang type and to me it is not straight forward to get it setup.

What was the actual behavior?
The [provided setup/compile command](https://github.com/cloudfoundry/libbuildpack/tree/master/packager ) did not make it compile as expected but errored out with:
```
go get github.com/cloudfoundry/libbuildpack
cd ~/go/src/github.com/cloudfoundry/libbuildpack/packager/buildpack-packager && go install

main.go:15:2: cannot find package "github.com/google/subcommands" in any of:
	/usr/lib/golang/src/github.com/google/subcommands (from $GOROOT)
	/home/bernhard/go/src/github.com/google/subcommands (from $GOPATH)
```

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by astrieanna** [comment]
Hi @drahnr, are you trying to push an app or build a custom buildpack?

If you want to push a statically compiled binary, you can push your app with the binary_buildpack we release; you do not need to build the buildpack itself.

**Comment by drahnr** [comment]
@astrieanna where would I download that? (I moved to manifest based deployment in the meantime, I'd just like to understand how this is supposed to work).

**Comment by astrieanna** [comment]
@drahnr You can push with a buildpack url, as described in https://docs.cloudfoundry.org/buildpacks/binary/index.html#-push-an-app .

**Comment by benjaminstokes** [comment]
I Ran into this issue tonight, so its still around. I just installed the package to resolve it. 

C:\Users\BenS\go\src\github.com\cloudfoundry\libbuildpack\packager\buildpack-packager>go install
main.go:15:2: cannot find package "github.com/google/subcommands" in any of:
        C:\Go\src\github.com\google\subcommands (from $GOROOT)
        C:\Users\BenS\go\src\github.com\google\subcommands (from $GOPATH)

C:\Users\BenS\go\src\github.com\cloudfoundry\libbuildpack\packager\buildpack-packager>echo %GOPATH%
C:\Users\BenS\go

C:\Users\BenS\go\src\github.com\cloudfoundry\libbuildpack\packager\buildpack-packager>gom
'gom' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\BenS\go\src\github.com\cloudfoundry\libbuildpack\packager\buildpack-packager>go get github.com/google/subcommands
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
        ignoring ..\..\go.mod;
        see 'go help modules'

C:\Users\BenS\go\src\github.com\cloudfoundry\libbuildpack\packager\buildpack-packager>go install

C:\Users\BenS\go\src\github.com\cloudfoundry\libbuildpack\packager\buildpack-packager>
