### ISSUE TITLE
Typo in buildpack names

### ISSUE THREAD

**Issue by acohen716** [cloudfoundry/binary-buildpack#25]
https://github.com/cloudfoundry/binary-buildpack/blob/ec05f7e30b8ab84d0b7f91d536136ee4c898cb91/bin/release.bat#L4

`hwc-buildpack` should be `hwc_buildpack` and `binary-buildpack` should be `binary_buildpack`

**Comment by sclevine** [comment]
`hwc_buildpack` and `binary_buildpack`  often identify the default system buildpacks on a deployment of Cloud Foundry, but in other contexts we use `-` to separate parts of the buildpack names.

(There is no guarantee that these buildpacks will be identified as `hwc_buildpack` and `binary_buildpack` in CF, especially if more than one version is available.)

**Comment by acohen716** [comment]
Thanks for the clarification. Since it's the default, shouldn't it use the `_`? Taking a look at the [HWC Buildpack push an app documentation](https://docs.cloudfoundry.org/buildpacks/hwc/index.html#push-your-app), it specifies `cf push APP-NAME -s windows2016 -b hwc_buildpack`. Taking a look at the [Binary Buildpack push an app documentation](https://docs.cloudfoundry.org/buildpacks/binary/index.html#pushing_apps), it specifies `cf push my_app -c './app' -b binary_buildpack`. This has come up in a workshop for students that are new to CF and push a .NET app using the `binary_buildpack` and not the `hwc_builpack`. Based on the error message they then try `hwc-buildpack` which doesn't exist. An alternative might be to use a space to separate and a recommendation to run `cf buildpacks` to find the exact builpack name?

**Comment by sclevine** [comment]
We would accept a PR that changed the phrasing to "Binary Buildpack" and "HWC Buildpack"

**Comment by tylerphelan** [comment]
Fixed on `develop` and will be in the next release!
