### ISSUE TITLE
Checksum mismatch for offline buildpack

### ISSUE THREAD

**Issue by dinomiteX** [cloudfoundry/binary-buildpack#29]
Hey everyone,

While trying to build the offline binary-buildpack i get the following Error:

`go build '-ldflags=-s -w' -o bin/supply ./src/binary/supply/cli
go: downloading github.com/cloudfoundry/libbuildpack v0.0.0-20181203192608-40fcf6231d2e
go: verifying github.com/cloudfoundry/libbuildpack@v0.0.0-20181203192608-40fcf6231d2e: checksum mismatch
	downloaded: h1:kHxAIoqlm9ABNd45IYQ+5TjBgLu3jkoBIqssOkkH0UQ=
	go.sum:     h1:n5B4kVCmuOwi7Q98xvHqEDYwpKBBB96lmlN/zaS7+bc=`

I have tried to update the module in the go.mod file to use the latest version supported in the go-buildpack **github.com/cloudfoundry/libbuildpack v0.0.0-20190110200243-27d5cb5e3702**

It worked. 

It would be great to update the libbuildpack module in the go.mod section. 

I guess @cf-buildpacks-eng is the right "person" to change it.

Thanks
Timo

**Comment by kardolus** [comment]
@dinomiteX thanks! I just fixed this on develop and master, which are now using the latest libbuildpack
