### ISSUE TITLE
.net IBM Bluemix 

### ISSUE THREAD

**Issue by Saloed123** [cloudfoundry/binary-buildpack#35]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`)?

   "name": "IBM Cloud",
   "build": "v11.2.0",
   "support": "http://ibm.biz/bluemix-supportinfo",
   "version": 0,
   "description": "IBM Bluemix",
   "authorization_endpoint": "https://iam.cloud.ibm.com/cloudfoundry/login/us-south",
   "token_endpoint": "https://uaa.us-south.cf.cloud.ibm.com",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "app_ssh_endpoint": "ssh.us-south.cf.cloud.ibm.com:2222",
   "app_ssh_host_key_fingerprint": "c7:1f:89:2a:62:3b:78:a9:08:c9:33:81:fb:39:26:da",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.us-south.cf.cloud.ibm.com:443",
   "api_version": "2.141.0",
   "osbapi_version": "2.15",
   "user": "97f2c047-b1a5-4ec8-a496-8284558ca96e"
}
cf.exe version 6.41.0+dd4c76cdd.2018-11-28

What version of the buildpack you are using?
ibmcloud cf push X -b https://github.com/cloudfoundry/binary-buildpack.git#v1.0.35

If you were attempting to accomplish a task, what was it you were attempting to do?
Can`t even install the buildpack.
After push command with -b .git, new buildpack not showing in CLI.
![image](https://user-images.githubusercontent.com/14234988/68195322-55831080-ffbf-11e9-9a99-e00484f44f7b.png)

What did you expect to happen?
Expect see you buildpack in ibm cli console

What was the actual behavior?
Not exist.
Maybe I not understand something. But I really try to find a solution, now I need help. Maybe I need to look at another side. I`m a newbie with Cloud and can do baby bugs.
Thanks.

Task: 
Deploy a .net framework console to IBM for scaling.
API .net Core already deployed, but with framework not so easy.
IBM CLI provides only one stack "cflinuxfx3" and I can`t find way to create one more "windows".

Will be thankful for topics, videos or any important/useful info.

Please confirm where necessary:
* [+] I have included a log output
* [ ] My log includes an error message
* [+ ] I have included steps for reproduction

**Comment by ryanmoran** [comment]
Hi @Saloed123! The `cf push` command will build and deploy an application using a buildpack. When you provide the `-b` flag with a URL to a buildpack, that buildpack is downloaded only for the building of this specific application. It will not show up in the list of global buildpacks available on the platform.

If you'd like to create a globally available buildpack, you may find [these docs](https://docs.cloudfoundry.org/adminguide/buildpacks.html) useful.

You also mention that you cannot create a "windows" stack. Stacks are configured and maintained by the platform administrator. If you need a new stack, your administrator should be able to include that new stack in the platform.

Cheers!

**Comment by ForestEckhardt** [comment]
We're gonna close this as inactive. Please feel free to re-open if you have further issues.
